### PR TITLE
Tidying up some formatting

### PR DESCRIPTION
**Pull request by Dokotela**
I loved your package, it's simple, elegant, and the only one I've found that works well in dart/flutter.

There were a few things I wanted to add to it, and I thought I'd open a PR in case you wanted to include any of them in the actual package.

1. I removed the requirement on quiver (again, not as clean, but less requirements on the outside world).
2. Added in lots of formatting for Strings. I needed to format a bunch of strings with special characters, xml code, escape characters, etc. So I've added in an extra function to handle all of these (and a list of all the special characters).
3. I appreciate the ability to sort the values if I want to, but often I didn't, so I made this optional.
4. Because I had a lot of long lines of text, I wanted to shorten them. I added a formatter that cuts them down to ~80 characters per line
5. The final return statement for toYamlString I'm not particularly proud of, but I haven't yet come up with a better way of moving the values next to the hyphen in lists instead of below.

As I said, it's not as elegant as your original package, but because I needed it to perform a little differently, I thought I'd check if you wanted to include any of them. Thanks!

### CODE REVIEW

**Comment by marcusedu** [comment]
hello @luuillu please approves this PR.

**Comment by Dokotela** [comment]
I needed to include this in one of my packages, so I published a fork. It's basically just the above changes. Feel free to look: https://pub.dev/packages/fhir_yaml

**Review by jamescardona11 — COMMENTED** [review]
I see the changes and tested in my side.
A good approach

**Comment by luuillu** [comment]
@Dokotela Thank you very much for your excellent idea contributed to this library.  the code already merged into master branch. I have published a new version package on pub.dev.

**Comment by Dokotela** [comment]
@luuillu Happy to have helped! Thanks for creating the package!

**Pull request merged**
